/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cloud_web_natives_NativeTools */

#ifndef _Included_org_cloud_web_natives_NativeTools
#define _Included_org_cloud_web_natives_NativeTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cloud_web_natives_NativeTools
 * Method:    watchFile
 * Signature: (Ljava/lang/String;Ljava/util/function/Consumer;)V
 */
JNIEXPORT void JNICALL Java_org_cloud_web_natives_NativeTools_watchFile
        (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif

